# -*- coding: utf-8 -*-
"""English texts of the catalog. Class names quoted in texts use “…” and MUST match an English display name
(checked by tools/validate.py)."""

# display-name overrides (key = yamnet index); all other classes use the official AudioSet name
NAME_OVERRIDES = {
    1: "Child speech", 3: "Narration or monologue", 18: "Chuckle", 19: "Crying", 20: "Baby cry", 22: "Wail or moan",
    48: "Footsteps", 59: "Heartbeat", 65: "Crowd chatter (hubbub)", 68: "Pets", 75: "Dog whimper", 81: "Farm animals",
    84: "Horse neigh", 85: "Cattle", 94: "Chicken or rooster", 96: "Rooster crow", 107: "Bird song", 108: "Chirp",
    110: "Pigeon or dove", 117: "Canids (dogs, wolves)", 118: "Rodents", 124: "Housefly", 126: "Bee or wasp",
    289: "Waves", 302: "Car horn", 312: "Air horn", 321: "Traffic noise", 364: "Water tap", 393: "Smoke detector",
    421: "Gunshot", 428: "Burst or pop", 436: "Glass clink", 437: "Shattering glass", 439: "Splash", 444: "Trickle",
    453: "Whoosh", 454: "Thud", 461: "Slap", 462: "Whack", 463: "Smash or crash", 473: "Crumpling", 475: "Beep",
    489: "Jingle",
}

CATEGORIES = {
    'voice': "Human voice", 'body': "Body and activities", 'crowd': "Crowds and groups", 'pets': "Pets",
    'farm_animals': "Farm animals", 'wildlife': "Wild animals, birds, insects", 'music': "Music",
    'alarms': "Alarms, bells and signals", 'nature': "Wind, storms and fire", 'water': "Water and liquids",
    'vehicles': "Vehicles and engines", 'home': "Household sounds", 'tools_mechanisms': "Tools and mechanisms",
    'impacts_explosions': "Impacts, breaking and gunshots", 'onomatopoeia': "Generic sounds (onomatopoeia)",
    'noise_ambience': "Noise, acoustics and microphone diagnostics", 'reproduced_sound': "Reproduced sound (TV, radio)",
    'misc': "Miscellaneous",
}

USAGES = {
    'security': "Security", 'fire': "Fire", 'door': "Door and visitors", 'baby': "Baby", 'animals': "Animals",
    'leaks': "Water and leaks", 'kitchen': "Kitchen", 'presence': "Presence", 'voiceless_command': "Voiceless commands",
    'outdoor': "Outdoor", 'weather': "Weather", 'garage': "Garage and car", 'pests': "Pests", 'comfort': "Comfort",
    'ambience': "Ambience", 'context': "Context", 'diagnostic': "Microphone diagnostics", 'other': "Other uses",
}

CAUSES = {
    'television': "television", 'radio': "radio", 'music': "music", 'broadcast_voice': "voice from a loudspeaker (call to prayer, announcements)",
    'voice_assistant': "voice assistant", 'smart_speakers': "smart speakers", 'street': "street", 'video_calls': "video calls",
    'fireworks': "fireworks and firecrackers", 'children_playing': "children playing", 'schoolyard': "nearby schoolyard",
    'neighbors': "neighbours", 'works': "construction work", 'animals': "animals", 'neighbor_dogs': "neighbours' dogs",
    'cat_meows': "cat meows", 'door_slam': "slamming door", 'impacts': "impacts", 'gps': "GPS", 'frying': "frying",
    'fireplace': "fireplace", 'neighbor_alarms': "neighbourhood alarms", 'building_alarm_drill': "neighbouring building alarm or drill",
    'other_device_alarms': "alarms of other devices", 'tv_doorbells': "doorbells on television", 'phones': "phones",
    'neighbor_doorbells': "neighbours' doorbells", 'doorbells': "doorbell", 'chimes': "chimes", 'furniture': "furniture",
    'emergency_sirens': "ambulances and police in the street", 'appliance_beeps': "appliance beeps (microwave, oven, washing machine)",
    'microwave': "microwave oven", 'washing_machines': "washing machine and dishwasher", 'dropped_dishes': "dropped dishes or bottle",
    'thunder': "thunder", 'detectors': "detectors",
}

ENUM_HELP = {
    'interest': {
        'monitor': "class recommended as an alert for a home",
        'optional': "useful depending on your situation; enable it knowingly",
        'context': "not an alert: used to raise the thresholds of other classes (television, music, speech…)",
        'ignore': "of little use or too unreliable for a home; disabled by default",
    },
    'role': {
        'event': "an event you can report",
        'context': "describes the ambience (television, crowd, wind…) rather than an event",
        'diagnostic': "indicates the state of the microphone (mains hum, wind, distortion…)",
        'generic': "broad parent class: choose its sub-classes instead",
    },
    'sound_type': {
        'impulsive': "short (breaking glass, a knock)",
        'repeated': "repeats (crying, footsteps, beeps)",
        'tonal': "sustained tone (siren, smoke detector, doorbell)",
        'continuous': "lasts a long time (running water, engine, rain)",
        'variable': "very variable duration",
    },
    'false_positive_level': {
        'low': "rarely triggered by mistake", 'medium': "sometimes", 'high': "often (television, neighbours…)",
    },
    'privacy': {
        'normal': "no particular concern",
        'sensitive': "may reveal personal information; keep clips very short",
        'confidential': "conversations: no clip may be kept (clip_forbidden = true)",
    },
}

SETTING_HELP = {
    'threshold': "minimum score (0 to 1) for a detection to count; to be tuned, YAMNet scores are not calibrated",
    'min_duration_s': "minimum duration of sustained detection before reporting",
    'cooldown_s': "delay before the same sound can be reported again",
    'pre_roll_s': "seconds of audio kept before the trigger in a clip",
    'post_roll_s': "seconds of audio kept after the trigger",
    'clip_retention_days': "how long clips are kept; 0 = no clip",
}

NOTES = {
    'speech': "Speech: no clip must be kept. Useful only as context (“someone is talking”) to raise the thresholds of other classes.",
    'child_speech_kid_speaking_shared': "Same precautions as “Speech”: no clip, context only.",
    'speech_synthesizer': "Synthetic voice (voice assistant, announcements). Can be used to ignore sounds produced by your own assistants.",
    'shout': "Shout: parent class of “Yell”, “Whoop”, “Bellow” and “Children shouting”. Choose “Screaming” as the main alert and keep “Shout” as an option only.",
    'yell': "Yell: sub-class of “Shout”. Duplicate if “Shout” is selected; very sensitive to television and children.",
    'children_shouting': "Almost always a normal sound. Of little use for an alert.",
    'screaming': "Screams: the most useful class for security but also the most prone to false alerts (films, games, playing children). Confirm with a second signal (presence, door, camera) before any action.",
    'whispering': "Whispering: confidential and very unreliable. Do not keep clips.",
    'laughter_shared': "Of no use for an alert; sensitive for privacy.",
    'crying_sobbing': "Crying of a child or an adult. Redundant with “Baby cry” when watching an infant.",
    'baby_cry_infant_cry': "Baby cry: a very common use case. Sometimes confused with cat meows (see “Cries and screams”). Requiring at least 2 seconds of continuous detection reduces false alerts.",
    'whimper': "Whimper: close to weak crying and to “Dog whimper”. Very vague.",
    'wail_moan': "Wail or moan: interesting in theory for distress, but too unreliable to trigger an alert on its own.",
    'singing': "Singing: mostly useful as context (musical activity). A sung voice played through a loudspeaker (call to prayer, announcements) can also trigger it.",
    'chant': "“Chant”: a chant or a call to prayer broadcast outdoors can trigger this class, as well as “Speech” and “Middle Eastern music”.",
    'groan': "Groan. Do not use alone for fall or distress detection.",
    'whistling': "Whistling with the mouth. Close to a whistle (kettle, steam whistle): see “Whistles”.",
    'snoring': "Snoring: indicates that someone is sleeping in the room; sensitive, do not keep clips.",
    'cough': "Cough: potential health data, therefore sensitive. Do not keep clips.",
    'run_shared': "Footsteps: complement a presence sensor but do not replace it; depends heavily on the floor covering and the microphone.",
    'finger_snapping': "Can be used as a voiceless command (finger snap); to be tested.",
    'clapping': "Hand claps: can be used as a voiceless command. Confused with applause and some sharp impacts.",
    'heart_sounds_heartbeat_shared': "Not relevant in practice: confused with bass sounds or thumping.",
    'crowd': "Crowd: often the television or the street. Use only as context.",
    'hubbub_speech_noise_speech_babble': "Crowd chatter: several voices at once. Context only.",
    'children_playing': "Children playing: normal in most cases. Can be used to calm other classes (screams).",
    'animal': "Root class: do not select directly.",
    'domestic_animals_pets': "Parent class: do not select alone.",
    'dog': "Parent class: includes barking, howling, growling, etc. Choose the specific classes instead.",
    'bark': "Bark: the most useful class for dogs. Prefer “Bark” alone rather than “Dog” + “Bark” (duplicate).",
    'yip_shared': "Sub-class of “Dog”: redundant if “Bark” is already monitored.",
    'cat': "Parent class: includes meowing, purring, hissing.",
    'meow': "Meow: sometimes confused with a baby cry.",
    'hiss': "Hiss: close to a jet of air or steam (“Steam”, “Spray”).",
    'caterwaul': "Fighting cat cries: loud, close to screams or crying.",
    'livestock_farm_animals_working_animals': "Parent class.",
    'crowing_cock_a_doodle_doo': "Rooster crow: useful only if you keep roosters; otherwise a source of outdoor noise.",
    'wild_animals': "Parent class: do not select directly.",
    'bird': "Birds in general: acts as an indicator of outdoor ambience (microphone near an open window).",
    'canidae_dogs_wolves': "Class covering dogs and wolves: contains only “Growling” and “Howl” (not “Bark”). Redundant with “Dog” and noisier.",
    'mouse': "Mouse: possible in an attic or cellar, but very vague; test before building an alert on it.",
    'patter': "Patter: often confused with light rain or light footsteps.",
    'insect_shared': "Insects: unreliable indoors; confused with the humming of appliances.",
    'whale_vocalization': "No domestic interest; mostly triggers on low tonal sounds.",
    'music': "The most useful class of the music group: a single “music is playing” signal to raise the thresholds of other classes. The 140+ other music classes (instruments, genres) are ignored by default.",
    'bell': "Parent class of bells (church, bicycle, sleigh bell, chime, tuning fork, cow bell). Does not contain “Doorbell” but sounds close to it.",
    'church_bell': "Church bell: outdoor sound; close to a doorbell depending on the microphone.",
    'middle_eastern_music': "Can trigger on a call to prayer or a chant broadcast by loudspeaker.",
    'lullaby': "Lullaby: of no use for detection; part of the “Music” set.",
    'wind': "Wind: used to put other outdoor detections into perspective.",
    'wind_noise_microphone': "Wind in the microphone: indicates that the microphone is exposed to a draught (open window, ventilation). Use it to decide where to move the microphone.",
    'thunderstorm': "Thunderstorm: can drive automations (close shutters, protect equipment). Confused with heavy construction work.",
    'thunder': "Thunder: confused with muffled gunshots.",
    'water': "Parent class of water: do not select directly.",
    'rain_shared': "Rain: useful as context (window left open, laundry outside) and to raise the thresholds of other classes. Confused with white noise and frying.",
    'steam': "Steam: confused with air jets and white noise.",
    'fire': "Fire: do NOT use as a reliable fire alert (crackling is very close to frying or rain). Keep for context.",
    'crackle': "Crackle: confused with rain, frying and static.",
    'vehicle': "Root class of vehicles: do not select.",
    'vehicle_horn_car_horn_honking_shared': "Horns: street sounds, of no interest for the home.",
    'car_alarm': "Car alarm: useful only if the vehicle is within earshot. Repeats in the street, hence many unimportant alerts.",
    'reversing_beeps': "Reversing beeps: confused with other beeps.",
    'traffic_noise_roadway_noise': "Traffic: indicates the outdoor ambience; useful to raise thresholds near a window.",
    'engine': "Parent class of engines: very broad.",
    'engine_starting': "Engine starting: possible for a garage or a nearby car (arrival, departure).",
    'idling': "Idling engine: for example a car running in a closed garage. Detects the noise, not carbon monoxide.",
    'door': "Parent class of “Doorbell”, “Knock”, “Slam”: do not select together with its children.",
    'doorbell': "Doorbell: useful to notify and to trigger a camera. Electronic melody doorbells are detected better than simple beeps.",
    'ding_dong': "Sub-class of “Doorbell”: duplicate if it is already monitored. Useful as a complement for two-tone doorbells.",
    'slam': "Door slam: confused with gunshots (firecrackers) and falling objects.",
    'knock': "Knock: useful to notify a visit when the doorbell is missing or broken.",
    'tap': "Tap: too general (keyboard, fingers, table).",
    'microwave_oven': "Microwave oven (mostly its end-of-cycle beeps). Source of FALSE alerts on “Smoke detector”: see the combination rules.",
    'water_tap_faucet_shared': "Running water: link it to a duration (tap left open). Confused with the shower and white noise.",
    'toilet_flush': "Toilet flush: a flush that runs continuously can be detected with a duration.",
    'vacuum_cleaner': "Vacuum cleaner: very recognizable. Useful to ignore other detections during cleaning.",
    'keys_jangling': "Keys jangling: a hint of arrival at the door, but unreliable alone.",
    'typing': "Typing: indicates presence; sensitive.",
    'alarm': "Parent class of almost all alarm signals: very broad, therefore very noisy. Prefer the specific classes.",
    'telephone': "Parent class of all telephone ring sounds.",
    'telephone_bell_ringing': "Landline telephone ring. Confused with the doorbell.",
    'ringtone': "Mobile ringtone: interesting to find a phone or to know it is ringing alone, but very variable (melodies).",
    'alarm_clock': "Alarm clock ringing: can be used to check that an alarm clock did ring; confused with other beeps.",
    'siren': "Siren in general: parent class of vehicle sirens. Mostly an indicator of what is happening in the street.",
    'buzzer': "Buzzer: intercom, building door release, timers. Very close to appliance beeps.",
    'smoke_detector_smoke_alarm': "The most useful use case. Require sustained detection of at least 3 seconds: an isolated beep must not trigger. It is NOT a replacement for a real smoke detector: it is a redundancy that listens to an existing detector.",
    'fire_alarm': "Fire alarm (building siren for example). Close to “Smoke detector”: choose only one as the main alert, the other as confirmation.",
    'whistle': "Whistle: can detect a whistling kettle, but is confused with mouth whistling.",
    'steam_whistle': "Steam whistle: kettle or pressure cooker. To be tested.",
    'air_conditioning': "Air conditioning: continuous noise. Mostly useful to understand why a microphone picks up constant background noise.",
    'hammer_shared': "Tools and works: rather neighbourhood noise than useful events.",
    'explosion': "Explosion: broad parent class of detonations. Loud and not very specific.",
    'gunshot_gunfire': "Gunshot: never trigger a heavy automatic action on this class alone. In regions where firecrackers or fireworks are common, expect many false alerts.",
    'fireworks': "Fireworks: use as context to raise the thresholds of “Gunshot”, “Explosion” and “Burst or pop” during festivities.",
    'firecracker': "Firecracker: same as “Fireworks”; frequently confused with a gunshot.",
    'glass': "Parent class of “Shattering glass” and “Glass clink”: choose “Shattering glass” instead.",
    'chink_clink': "Glass clink: meals, glasses clinking together. Very frequent, of little use.",
    'shatter': "Shattering glass: useful for security (broken window). Confirm with a window sensor or a camera: dropped dishes are frequent.",
    'liquid': "Broad parent class: do not select directly.",
    'drip': "Drip: can signal a tap or a leak, provided the microphone is close and the environment is quiet.",
    'gush': "Gush: possible hint of a major leak. Detects the noise, not the leak: pair it with a water sensor.",
    'fill_with_liquid': "Filling: useful for a bathtub or a bucket being filled. Combine with a duration (for example more than 10 minutes).",
    'boiling': "Boiling: can signal a pot or a kettle boiling. Does not replace a stove safety device.",
    'thump_thud': "Thud: a falling object or person, furniture, neighbours. Do not use alone for fall detection.",
    'breaking': "Breaking in general (not only glass): broader, therefore more false alerts.",
    'beep_bleep': "Appliance beeps (end of cycle). Very common, so group with “Microwave oven”; do not make it a fire alert.",
    'ding': "Ding: confused with the doorbell and timers.",
    'clatter': "Clatter of objects falling or knocking together.",
    'sizzle': "Sizzle: pan cooking. Detects a cooking noise, not a danger.",
    'silence': "Silence: if this class is constant while there is activity, the microphone is probably muted or badly connected.",
    'inside_small_room_shared': "Describes the acoustics of the place (room, outdoors) rather than an event: useful only to understand the microphone's environment.",
    'static_shared': "Microphone quality indicator: a constantly high value often signals a noisy or saturated microphone.",
    'mains_hum': "Mains hum (50/60 Hz): if permanently high, the microphone picks up electrical noise (power supply, ground loop). Fix on the wiring side.",
    'television': "Television is the first cause of false alerts. As a CONTEXT class, it raises the thresholds of screams, gunshots, barks and doorbells while it is on.",
    'radio': "Same use as “Television”: signals that a sound comes from a loudspeaker, not from the room.",
}

GROUPS = {
    'dogs': ("Dogs",
        "“Dog” contains “Bark”, “Yip”, “Bow-wow”, “Growling”, “Howl” and “Dog whimper”: a bark often activates “Dog” at the same time. “Canids (dogs, wolves)” contains only “Growling” and “Howl”.",
        "Monitor “Bark” alone. Add “Howl” only if howling interests you."),
    'cats': ("Cats",
        "“Cat” includes the others. Shrill meows resemble a baby crying.",
        "Choose “Meow” alone; do not combine it with a baby-cry alert without a confirmation rule."),
    'cries_and_screams': ("Cries and screams",
        "High-pitched, plaintive sounds that get confused with each other (baby, cat, human scream, squeal).",
        "If you watch a baby: “Baby cry” with at least 2 seconds of continuous detection; ignore the others."),
    'shouts': ("Shouts and calls",
        "Playing children, TV matches and films often trigger these classes.",
        "Keep “Screaming” (and possibly “Shout”) with a high threshold; use “Television” as context."),
    'speech': ("Speech, voices and vocal context",
        "Privacy: these classes detect conversations. They get confused with television and radio.",
        "Never keep a clip. Use them as context (“someone is talking”) rather than as an alert."),
    'sung_voice': ("Sung voice, chant and broadcast prayer",
        "A sung or chanted voice broadcast by a loudspeaker (call to prayer, announcements) activates several of these classes, as well as “Speech”.",
        "Do not make them alerts. If these sounds are frequent where you live, raise the thresholds of the other vocal classes at those times."),
    'detonations': ("Detonations and sharp impacts",
        "Firecrackers, fireworks, slamming doors and thunder are easily mistaken for a gunshot.",
        "Never trigger a heavy action on these classes alone. Use “Fireworks” and “Firecracker” as inhibiting context."),
    'glass_breaking': ("Glass and breaking",
        "Dropped or clinking dishes resemble breaking glass.",
        "Keep “Shattering glass” alone for security; “Breaking” and “Clatter” as options. Confirm with an opening sensor or a camera."),
    'fire_alarms_and_beeps': ("Fire alarms and appliance beeps",
        "An isolated beep from a microwave or washing machine can resemble a smoke detector.",
        "For the fire alert: “Smoke detector” and “Fire alarm” with at least 3 seconds of sustained detection. Do not add “Beep” as an alert."),
    'doorbells_and_bells': ("Doorbells, ringtones and bells",
        "Telephone rings, television rings and bells are close to a doorbell.",
        "For the door: “Doorbell” alone. Telephone rings and bells stay out of alerts."),
    'sirens_and_horns': ("Sirens and horns",
        "Very frequent street sounds, confused with each other and with television.",
        "Useful only as an outdoor indicator; do not trigger a home alert."),
    'whistles': ("Whistles",
        "A whistling kettle, mouth whistling and a steam leak are close.",
        "Test with your kitchen before building an automation."),
    'doors_and_knocks': ("Doors, knocks and bangs",
        "Knocks, drawers and furniture get confused. “Door” includes several sounds.",
        "Choose “Knock” for a visit, “Slam” for slamming; avoid “Door” and “Tap”."),
    'running_water': ("Running water, leaks",
        "A tap, the shower, rain and white noise sound alike. None of these classes detects water: only its noise.",
        "Always pair with a duration and a real water sensor for leaks."),
    'continuous_motors': ("Motors and continuous appliances",
        "Continuous noises that get confused with each other and mask other sounds.",
        "Treat them as context: they mostly explain why other classes are less sensitive."),
    'footsteps_presence': ("Footsteps and presence",
        "A presence sensor does better. Footsteps depend on the floor, the microphone and the neighbours.",
        "Use as a complement to a presence sensor, not instead of it."),
    'coughs_and_breathing': ("Coughs, sneezes and breathing",
        "Sounds close to each other; they relate to health, therefore sensitive.",
        "Do not keep clips. Reserve for discreet presence uses."),
    'insects_rodents': ("Insects and rodents",
        "Very faint and very close to appliance or plumbing noises.",
        "Unreliable; try only with a nearby microphone (attic, cellar)."),
    'birds': ("Birds",
        "“Bird” includes almost all the other classes of this group.",
        "Useful only as an indicator of outdoor ambience."),
    'street_vehicles': ("Vehicles in the street",
        "Omnipresent street sounds; a microphone near a window picks them up continuously.",
        "Use them as outdoor context; ignore their events."),
    'fire_crackle': ("Fire, crackle and cooking",
        "Fire, frying, rain and static sound very much alike.",
        "Do not use “Fire” as a fire alert. Rely on a real smoke detector."),
    'mic_diagnostics': ("Microphone quality diagnostics",
        "These classes do not describe an event in the house but the state of the microphone and its wiring.",
        "Watch them during setup: a constant “Mains hum”, wind or distortion points to a hardware problem."),
    'music_general': ("Music",
        "Background music activates many classes (voices, instruments, bells).",
        "Keep “Music” as context; ignore instruments and genres."),
}

RULES = {
    'fire_double': "“Smoke detector” and “Fire alarm” are very close: one event can trigger both. Use the same action for both and count a single alert (cooldown).",
    'fire_beeps': "“Beep” also triggers on microwave ovens and washing machines: do not use it as a fire alert, and require sustained detection of at least 3 seconds for “Smoke detector”.",
    'fire_only': "“Fire” and “Crackle” get confused with frying and rain: do not use them as a fire alert.",
    'detonations_fireworks': "Fireworks and firecrackers get confused with gunshots. Use “Fireworks” and “Firecracker” as inhibiting context, not as events, and do not trigger a heavy action on “Gunshot” alone.",
    'doorbell_duplicates': "Several doorbell/bell classes trigger at the same time. Keep “Doorbell” as the main alert.",
    'doorbell_phone': "Telephone rings can trigger “Doorbell”. Measure the confusions at home before automating.",
    'baby_cat': "Meows (especially cat cries) are sometimes classified as a baby cry: require sustained detection of at least 2 seconds and a suitable threshold.",
    'multiple_shouts': "These classes are neighbours: choose one as the main alert (for example “Screaming”). The others will produce duplicate alerts.",
    'glass_duplicates': "“Glass” is the parent of “Shattering glass”: choose “Shattering glass” alone, and “Breaking” or “Smash or crash” as an option with a higher threshold.",
    'dog_duplicates': "“Dog” contains “Bark” (and “Yip”, “Bow-wow”, “Growling”, “Howl”): a bark triggers both. Keep “Bark”. “Canids (dogs, wolves)” is redundant and noisier.",
    'speech_target': "Speech classes: they detect conversations. No clip must be kept; use them only as context.",
    'water_leak': "These classes detect the noise of water, not water. For a leak, add a real water sensor and a minimum duration (for example 5 to 10 minutes).",
    'music_classes': "When music plays, many classes (voices, instruments, bells) activate. Monitor “Music” as context rather than its sub-classes.",
    'context_recommended': "These classes are sensitive to television and radio. Add “Television” and “Radio” as context to raise the thresholds automatically.",
}

AUTO_RULES = {
    'parent_child': "“{parent}” contains “{child}”: one sound will trigger both. Keep the more precise one, or the broader one, but not both with different rules (retention, threshold, action).",
    'clip_forbidden': "“{class}” detects conversations: no clip may be kept. Retention is forced to 0.",
    'low_threshold_high_fp': "“{class}” is often triggered by mistake; a threshold this low will multiply false alerts. Add an inhibiting context (television, radio, music).",
    'generic_class': "“{class}” is a broad parent class: prefer its sub-classes ({examples}).",
    'missing_context': "“{class}” is sensitive to television, radio or music: select them as context classes to raise the thresholds automatically.",
    'schedule_gap_safety': "“{class}” is a safety class, but the schedule of “{source}” leaves gaps: it will not be listened for during those hours. Give the class its own continuous schedule to keep it active at all times.",
    'volume_gate_safety': "The minimum volume of “{source}” ({gate} dBFS) is high for “{class}”: a distant or muffled alarm may fall below it and be missed. Lower the gate or set a lower one for this class.",
    'clip_source_disallowed': "Clips are disabled on “{source}”: the retention of “{class}” is forced to 0 there.",
}
AUTO_RULES_FR_EXTRA = {
    'schedule_gap_safety': ("la source a un planning avec des trous et une classe de sécurité n'a pas de planning propre",
        "« {class} » est une classe de sécurité, mais le planning de « {source} » laisse des trous : elle ne sera pas écoutée à ces heures. Donnez à la classe son propre planning continu pour qu'elle reste active en permanence."),
    'volume_gate_safety': ("volume minimum effectif supérieur à -40 dBFS sur une classe de sécurité",
        "Le volume minimum de « {source} » ({gate} dBFS) est élevé pour « {class} » : une alarme lointaine ou étouffée peut passer sous ce seuil et être manquée. Baissez le seuil de volume ou fixez-en un plus bas pour cette classe."),
    'clip_source_disallowed': ("clips désactivés sur la source alors que la classe autorise la conservation",
        "Les clips sont désactivés sur « {source} » : la conservation de « {class} » y est forcée à 0."),
}
AUTO_RULES_DESC = {
    'en': {
        'parent_child': "a selected class is an ancestor (ancestors / descendants) of another selected class",
        'clip_forbidden': "clip_retention_days > 0 on a class whose clip_forbidden is true",
        'low_threshold_high_fp': "threshold below the suggested threshold on a class whose false_positives.level is high",
        'generic_class': "role is generic",
        'missing_context': "class with non-empty inhibiting_contexts and no context class selected",
        'schedule_gap_safety': "the source has a schedule with gaps and a safety class has no schedule of its own",
        'volume_gate_safety': "effective minimum volume above -40 dBFS on a safety class",
        'clip_source_disallowed': "clips disabled on the source while the class allows retention",
    },
    'fr': {
        'parent_child': "une classe sélectionnée est un ancêtre (ancestors / descendants) d'une autre classe sélectionnée",
        'clip_forbidden': "clip_retention_days > 0 sur une classe dont clip_forbidden vaut vrai",
        'low_threshold_high_fp': "seuil inférieur au seuil suggéré sur une classe dont false_positives.level vaut high",
        'generic_class': "role vaut generic",
        'missing_context': "classe avec inhibiting_contexts non vide, sans aucune classe de contexte sélectionnée",
    },
}

UI = {
    'en': {'catalog_title': "Sound class catalog (YAMNet)", 'language_name': "English"},
    'fr': {'catalog_title': "Catalogue des classes de sons (YAMNet)", 'language_name': "Français"},
}
