"""Loads the built panel in headless Chromium against a stand-in for Home Assistant, checks behaviour and writes screenshots.
Usage: python3 test/run.py [output_dir]   (after `npm run build`)"""
import http.server, json, os, sys, threading
from playwright.sync_api import sync_playwright

HERE = os.path.dirname(os.path.abspath(__file__))
BUILD = os.path.join(HERE, "..", "..", "custom_components", "sound_recognition", "frontend", "sound-recognition-panel.js")
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "out")
os.makedirs(OUT, exist_ok=True)
sys.path.insert(0, os.path.join(HERE, "..", "..", "service"))
from soundrec import catalog as _cm
CATALOGS = {f"/catalog_{lang}.json": json.dumps(_cm.load_lang(lang)).encode() for lang in ("en", "fr")}   # the real 521-class catalog


class H(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        path = self.path.split("?")[0]
        files = {"/": ("harness.html", "text/html"), "/panel.js": (BUILD, "text/javascript"), "/clip.wav": (None, "audio/wav")}
        if path == "/favicon.ico":
            self.send_response(204); self.end_headers(); return
        if path in CATALOGS:
            self.send_response(200); self.send_header("Content-Type", "application/json"); self.end_headers(); self.wfile.write(CATALOGS[path]); return
        if path not in files:
            self.send_response(404); self.end_headers(); return
        name, ctype = files[path]
        body = b"RIFF" if name is None else open(name if os.path.isabs(name) else os.path.join(HERE, name), "rb").read()
        self.send_response(200); self.send_header("Content-Type", ctype); self.end_headers(); self.wfile.write(body)

    def log_message(self, *a): pass


srv = http.server.ThreadingHTTPServer(("127.0.0.1", 0), H)
threading.Thread(target=srv.serve_forever, daemon=True).start()
base = f"http://127.0.0.1:{srv.server_port}/"


def text(page, sel):
    return page.evaluate("""(sel) => { const walk = (r) => { const out = []; r.querySelectorAll('*').forEach(e => { if (e.shadowRoot) out.push(...walk(e.shadowRoot)); }); out.push(...r.querySelectorAll(sel)); return out; }; return walk(document).map(e => e.textContent.trim().replace(/\\s+/g, ' ')); }""", sel)


def ok(cond, msg):
    print(("PASS " if cond else "FAIL ") + msg)
    if not cond:
        ok.failed = True
ok.failed = False

with sync_playwright() as p:
    b = p.chromium.launch(executable_path="/opt/pw-browsers/chromium", args=["--no-sandbox"])
    errors = []

    def new(query="", scheme="light", w=1200, h=800):
        pg = b.new_page(viewport={"width": w, "height": h}, color_scheme=scheme)
        pg.on("pageerror", lambda e: errors.append(str(e)))
        pg.on("console", lambda m: errors.append(m.text) if m.type == "error" else None)
        pg.add_init_script("window.__updatePollMs = 50")
        pg.goto(base + query)
        return pg

    pg = new()
    pg.wait_for_function("document.querySelector('sound-recognition-panel')?.shadowRoot?.querySelector('sound-recognition-live')?.shadowRoot?.querySelector('.card')")
    cards = text(pg, ".card")
    ok(len(cards) == 4, "four source cards")
    ok(any("Kitchen" in c and "Connected" in c and "-38 dBFS" in c for c in cards), "kitchen shows connection and level")
    ok(any("Garden camera" in c and "Below the volume gate" in c for c in cards), "gated source flagged")
    ok(any("Nursery" in c and "Starting" in c for c in cards) and any("Old Pi" in c and "Disabled" in c for c in cards), "starting and disabled states")
    ok(any("1 advice item" in t for t in text(pg, ".banner")), "advice banner")
    ev = text(pg, ".events li")
    ok(len(ev) == 3 and "Bark" in ev[0] and "91%" in ev[0] and "2 minutes ago" in ev[0], "stored events with names, score, relative time")
    ok(pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-live').shadowRoot.querySelectorAll('audio').length") == 2, "player only when a clip exists")
    # live messages
    pg.evaluate("window.__push({type:'active', source:'kitchen', active_classes:['/m/01y3hg']})")
    pg.evaluate("window.__push({type:'detection', id:'n1', source:'kitchen', mid:'/m/01y3hg', class:'Smoke', name:'Smoke detector', score:0.88, duration_s:2, detected_at:new Date().toISOString()})")
    pg.wait_for_timeout(200)
    ok(any("Active now" in c and "Smoke detector" in c for c in text(pg, ".card")), "live active class shown")
    ev = text(pg, ".events li")
    ok(len(ev) == 4 and "Smoke detector" in ev[0] and "just now" in ev[0], "live detection prepended")
    pg.evaluate("window.__push({type:'clip_ready', id:'n1', source:'kitchen', mid:'/m/01y3hg', clip:'k/n1.wav', clip_url:'/clip.wav', expires_at:'x'})")
    pg.wait_for_timeout(200)
    ok(pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-live').shadowRoot.querySelectorAll('audio').length") == 3, "clip attached to its detection")
    pg.evaluate("window.__push({type:'source_state', source:'kitchen', state:'disconnected', error:'boom'})")
    pg.wait_for_timeout(200)
    ok(any("Kitchen" in c and "Disconnected" in c for c in text(pg, ".card")), "connection loss shown")
    pg.evaluate("window.__push({type:'source_state', source:'kitchen', state:'connected'})")
    pg.evaluate("window.__push({type:'active', source:'kitchen', active_classes:[]})")
    pg.screenshot(path=os.path.join(OUT, "live-light.png"))
    pg.close()

    pg = new("?lang=fr", "dark")
    pg.wait_for_function("document.querySelector('sound-recognition-panel')?.shadowRoot?.querySelector('sound-recognition-live')?.shadowRoot?.querySelector('.card')")
    ok(any("Connecté" in c for c in text(pg, ".card")) and any("Aboiement" in e and "il y a 2 minutes" in e for e in text(pg, ".events li")), "French texts and catalog language")
    pg.screenshot(path=os.path.join(OUT, "live-dark-fr.png"))
    pg.close()

    pg = new("?narrow=1", "light", 390, 800)
    pg.wait_for_function("document.querySelector('sound-recognition-panel')?.shadowRoot?.querySelector('sound-recognition-live')?.shadowRoot?.querySelector('.card')")
    ok(pg.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "no horizontal scroll at phone width")
    ok(len(text(pg, ".menu")) == 1, "menu button when narrow")
    pg.screenshot(path=os.path.join(OUT, "live-phone.png"), full_page=True)
    pg.close()

    # ------------------------------------------------------------------ sources tab
    def deep(page, sel):
        return page.locator(sel)

    pg = new("", "light", 1200, 900)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("sound-recognition-sources li[data-source]")
    rows = text(pg, ".list li")
    ok(len(rows) == 2 and "Scheduled · 52.5 h per week" in rows[0] and "Clips up to 7 days" in rows[0], "source list with schedule and clips summary")
    ok("Listens continuously" in rows[1] and "Clips: default" in rows[1], "continuous source summary")
    # edit keeps hidden fields and untouched schedule windows byte for byte
    pg.click("li[data-source=kitchen] button[data-action=edit]")
    pg.wait_for_selector("sound-recognition-sources form")
    ok(pg.locator("sr-schedule-grid .cell.on").count() == 5 * 21, "grid shows 08:00-18:30 on weekdays (off-grid end widened)")
    pg.fill("input[name=name]", "Kitchen ESP32")
    pg.click("button[data-action=save]")
    pg.wait_for_selector("sound-recognition-sources .notice")
    saved = pg.evaluate("window.__state.saves.at(-1)")
    k = next(s for s in saved["sources"] if s["id"] == "kitchen")
    ok(k["name"] == "Kitchen ESP32" and k["classes"] == {"Smoke detector, smoke alarm": {"enabled": True}} and k["schedule"]["windows"] == [{"days": ["mon", "tue", "wed", "thu", "fri"], "from": "08:00", "to": "18:10"}], "edit keeps class settings and untouched windows")
    ok(saved["api"]["token"] == "***" and saved["classes"] == {"Bark": {"enabled": True}}, "rest of the configuration is sent back unchanged")
    ok("Gap in the schedule" not in text(pg, ".notice")[0], "no advice shown for another source")
    ok(pg.locator(".notice li").count() == 1 and "Same advice for" in text(pg, ".notice")[0], "three sounds with the same advice become one line that names the others")
    # add a source with a painted schedule
    pg.click("button[data-action=add]")
    ok(pg.locator("select[name=type]").input_value() == "go2rtc", "the form starts on go2rtc")
    pg.select_option("select[name=type]", "rtsp")
    pg.fill("input[name=row-name]", "Nursery ESP32")
    pg.fill("input[name=row-url]", "rtsp://x/n")
    pg.click("details.adv summary")
    pg.fill("input[name=offset]", "-0.1")
    pg.fill("input[name=minVolume]", "-50")
    pg.check("input[name=mode][value=scheduled]")
    pg.wait_for_selector("sr-schedule-grid .cell")
    ok(pg.locator("sr-schedule-grid .cell.on").count() == 0, "new schedule starts empty")
    pg.click("button[data-action=save]")
    ok(any("at least one time slot" in t for t in text(pg, ".errors")), "empty schedule is refused before saving")
    first = pg.locator("sr-schedule-grid .cell").nth(0).bounding_box()
    last = pg.locator("sr-schedule-grid .cell").nth(11).bounding_box()      # Monday 00:00-06:00 by dragging
    pg.mouse.move(first["x"] + 2, first["y"] + 2); pg.mouse.down(); pg.mouse.move(last["x"] + 2, last["y"] + 2, steps=8); pg.mouse.up()
    ok(pg.locator("sr-schedule-grid .cell.on").count() == 12, "dragging paints cells")
    pg.locator("sr-schedule-grid .day").nth(1).click()                      # whole Tuesday
    ok(pg.locator("sr-schedule-grid .cell.on").count() == 12 + 48, "clicking a day toggles it")
    pg.screenshot(path=os.path.join(OUT, "sources-form.png"), full_page=True)
    pg.click("button[data-action=save]")
    pg.wait_for_selector("sound-recognition-sources .notice")
    saved = pg.evaluate("window.__state.saves.at(-1)")
    n = saved["sources"][-1]
    ok(n["id"] == "nursery_esp32" and n["threshold_offset"] == -0.1 and n["min_volume_dbfs"] == -50 and n["schedule"]["mode"] == "scheduled", "new source saved with id, offset, gate")
    ok(n["schedule"]["windows"] == [{"days": ["mon"], "from": "00:00", "to": "06:00"}, {"days": ["tue"], "from": "00:00", "to": "00:00"}], "painted cells become service windows")
    ok(any("Gap in the schedule" in t for t in text(pg, ".notice")), "advice for the saved source is shown")
    pg.screenshot(path=os.path.join(OUT, "sources-list.png"), full_page=True)
    # go2rtc stream picker and adding several sources at once
    pg.click("button[data-action=add]")
    ok(pg.locator("select[name=type]").input_value() == "rtsp", "after an RTSP source the next form starts on RTSP")
    pg.select_option("select[name=type]", "go2rtc")
    pg.wait_for_selector("input[name=g2url]")
    ok(pg.locator("input[name=g2pick]").count() == 0 and pg.evaluate("window.__state.g2calls") == [None], "go2rtc asks for the remembered address first, none known yet")
    pg.fill("input[name=g2url]", "go2rtc-down")
    pg.click("button[data-action=g2-load]")
    pg.wait_for_selector("[data-g2-error]")
    ok("refused" in text(pg, "[data-g2-error]")[0] and pg.locator("input[name=g2pick]").count() == 0, "an unreachable go2rtc shows the reason and no list")
    pg.fill("input[name=g2url]", "192.168.1.5")
    pg.click("button[data-action=g2-load]")
    pg.wait_for_selector("input[name=g2pick]")
    ok(pg.evaluate("window.__state.g2calls.at(-1)") == "192.168.1.5" and pg.locator("input[name=g2url]").input_value() == "http://192.168.1.5:1984", "address is sent and replaced by the normalised one")
    ok(pg.locator("input[name=g2pick]").count() == 2 and pg.locator("[data-stream]").all_text_contents()[0].strip().startswith("salon"), "streams are offered as checkboxes")
    pg.locator("[data-stream=garage] input[name=g2pick]").check()
    ok(pg.locator("[data-stream=garage] input[name=g2name]").input_value() == "garage", "a checked stream proposes its own name")
    pg.fill("[data-stream=garage] input[name=g2name]", "Garage mic")
    pg.locator("[data-stream=salon] input[name=g2pick]").check()
    pg.click("button[data-action=row-add]")
    pg.locator("input[name=row-name]").nth(0).fill("Porch")
    pg.locator("input[name=row-url]").nth(0).fill("rtsp://10.0.0.7/porch")
    pg.locator("details.paste summary").click()
    pg.fill("textarea[name=paste]", "Cellar, rtsp://10.0.0.8:554/s1\n\nrtsp://10.0.0.9/attic\n")
    pg.click("button[data-action=paste-add]")
    ok(pg.locator("input[name=row-url]").count() == 3 and pg.locator("input[name=row-name]").nth(1).input_value() == "Cellar" and pg.locator("input[name=row-url]").nth(2).input_value() == "rtsp://10.0.0.9/attic", "a pasted list becomes rows (name, address; address alone)")
    pg.screenshot(path=os.path.join(OUT, "sources-go2rtc.png"), full_page=True)
    before = len(pg.evaluate("window.__state.saves"))
    pg.click("button[data-action=save]")
    pg.wait_for_function(f"window.__state.saves.length == {before + 1}")
    batch = pg.evaluate("window.__state.saves.at(-1).sources")[-5:]
    ok([(x["name"], x["url"], x["type"]) for x in batch] == [
        ("Garage mic", "rtsp://192.168.1.5:8554/garage", "go2rtc"), ("salon", "rtsp://192.168.1.5:8554/salon", "go2rtc"),
        ("Porch", "rtsp://10.0.0.7/porch", "go2rtc"), ("Cellar", "rtsp://10.0.0.8:554/s1", "go2rtc"), ("attic", "rtsp://10.0.0.9/attic", "go2rtc")],
       "five sources are added with one save (names from the stream, the row or the address)")
    ok(pg.locator(".notice li").count() <= 3 and text(pg, ".notice")[0].count("sensitive to television") == 1 and text(pg, ".notice")[0].count("Same advice for") == 1, "the same advice on five new sources is shown once, not five times")
    ok("Same advice for" in text(pg, ".notice")[0], "and names the other sounds")
    ok(len({x["id"] for x in pg.evaluate("window.__state.saves.at(-1).sources")}) == len(pg.evaluate("window.__state.saves.at(-1).sources")), "ids stay unique")
    pg.click("button[data-action=add]")
    ok(pg.locator("select[name=type]").input_value() == "go2rtc", "the next form starts on the last type used")
    pg.wait_for_selector("input[name=g2pick]")
    ok(pg.locator("[data-stream=salon] input[name=g2pick]").is_disabled() and "already added" in pg.locator("[data-stream=salon]").inner_text(), "streams already added are greyed out")
    pg.click("button[data-action=cancel]")
    # nothing to add is refused on the page; a refusal by the service is shown and nothing is saved
    pg.click("button[data-action=add]")
    pg.click("button[data-action=save]")
    ok(any("at least one" in t for t in text(pg, ".errors")), "adding nothing is refused on the page")
    pg.click("button[data-action=cancel]")
    pg.click("li[data-source=kitchen] button[data-action=edit]")
    pg.fill("input[name=url]", " ")
    pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-sources').shadowRoot.querySelector('input[name=url]').removeAttribute('required')")
    pg.click("button[data-action=save]")
    pg.wait_for_selector("sound-recognition-sources .errors")
    ok(any("url is required" in t for t in text(pg, ".errors")) and len(pg.evaluate("window.__state.saves")) == 3, "service refusal is shown and nothing is saved")
    pg.click("button[data-action=cancel]")
    # disable and remove
    pg.locator("li[data-source=garden] input[type=checkbox]").uncheck()
    pg.wait_for_function("window.__state.saves.length == 4")
    ok(pg.evaluate("window.__state.saves.at(-1).sources.find(s => s.id==='garden').enabled") is False, "toggle disables a source")
    pg.click("li[data-source=garden] button[data-action=remove]")
    ok(pg.evaluate("window.__state.saves.length") == 4, "removal asks for confirmation first")
    pg.click("li[data-source=garden] button[data-action=confirm-remove]")
    pg.wait_for_function("window.__state.saves.length == 5")
    ok(all(s["id"] != "garden" for s in pg.evaluate("window.__state.saves.at(-1).sources")), "source removed after confirmation")
    pg.close()

    # ------------------------------------------------------------------ sounds tab
    def sounds_root(page):
        return "document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-sounds').shadowRoot"

    def rows(page):
        return page.evaluate(sounds_root(page) + ".querySelectorAll('li[data-mid]:not(.inctx)').length")

    pg = new("", "light", 1200, 900)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sounds]")
    pg.wait_for_selector("sound-recognition-sounds li[data-mid]")
    ok(any("516 sounds" in t for t in text(pg, ".dim")), "the other 516 classes are listed (5 context sounds are grouped above)")
    ok(rows(pg) == 60, "list is paged")
    first = text(pg, "li[data-mid]:not(.inctx) .name")
    ok(all("Recommended alert" in f for f in first[:8]), "recommended alerts come first")
    pg.click("button[data-action=more]")
    ok(rows(pg) == 120, "show more adds a page")
    pg.fill("input[name=search]", "bark")
    pg.wait_for_timeout(100)
    names = text(pg, "li[data-mid] .name strong")
    ok("Bark" in names and 1 <= len(names) < 20, "search narrows the list")
    ok(any("Bark" in c for c in names), "search finds Bark")
    ok(pg.locator("sound-recognition-sounds li[data-mid]").first.locator("button.chip").count() == 2, "one chip per configured source in the all-sources view")
    # enable globally, save
    pg.fill("input[name=search]", "Bark")
    bark_row = pg.locator("sound-recognition-sounds li[data-mid='/m/05tny_']")
    ok(bark_row.locator("input[name=global]").is_checked(), "Bark is enabled globally in the stand-in configuration")
    pg.fill("input[name=search]", "Whistle")
    wh = pg.locator("sound-recognition-sounds li[data-mid]").first
    wh.locator("input[name=global]").check()
    ok(pg.locator("sound-recognition-sounds .savebar").count() == 1, "unsaved changes bar appears")
    wh.locator("button.chip[data-source=garden]").click()                         # explicit off on one source
    pg.click(".savebar button[data-action=save]")
    pg.wait_for_selector("sound-recognition-sounds .notice")
    saved = pg.evaluate("window.__state.saves.at(-1)")
    wkey = [k for k in saved["classes"] if k not in ("Bark",)][0]
    g = next(x for x in saved["sources"] if x["id"] == "garden")
    ok(saved["classes"][wkey] == {"enabled": True} and g["classes"][wkey] == {"enabled": False}, "global enable and per-source exception saved")
    ok(pg.locator("sound-recognition-sounds .savebar").count() == 0, "bar disappears once saved")
    # per-source scope: toggling back to the inherited state removes the override
    pg.select_option("select[name=scope]", "garden")
    pg.fill("input[name=search]", "Whistle")
    row = pg.locator("sound-recognition-sounds li[data-mid]").first
    ok(not row.locator("input[name=scoped]").is_checked(), "scope shows the effective state of the source")
    row.locator("input[name=scoped]").check()
    n_saves = pg.evaluate("window.__state.saves.length")
    pg.click(".savebar button[data-action=save]")
    pg.wait_for_function(f"window.__state.saves.length > {n_saves}")
    g = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "garden")
    ok(wkey not in (g.get("classes") or {}), "back to the inherited value drops the exception")
    # discard
    pg.locator("li[data-mid]").first.locator("input").first.click()
    ok(pg.locator("sound-recognition-sounds .savebar").count() == 1, "toggle marks unsaved")
    pg.click(".savebar button:not(.primary)")
    ok(pg.locator("sound-recognition-sounds .savebar").count() == 0, "discard restores the saved configuration")
    # recommended
    pg.select_option("select[name=scope]", "")
    pg.fill("input[name=search]", "")
    pg.click("button[data-action=recommended]")
    pg.check("input[name=onlyEnabled]")
    ok(rows(pg) >= 8, "recommended sounds are enabled")
    pg.click(".savebar button:not(.primary)")
    pg.uncheck("input[name=onlyEnabled]")

    # detail of a sound in one source: placeholders, applied values with reasons
    pg.select_option("select[name=scope]", "garden")
    pg.fill("input[name=search]", "Bark")
    pg.locator("li[data-mid='/m/05tny_'] button[data-action=settings]").click()
    pg.wait_for_selector("sound-recognition-sounds sr-class-detail input[name=threshold]")
    ph = pg.get_attribute("input[name=threshold]", "placeholder")
    ok(ph in ("0.6", "0.60"), f"inherited threshold placeholder is catalog 0.5 + source offset 0.1 (got {ph})")
    ok(any("0.6 — catalog suggestion + source offset" in t for t in text(pg, "[data-applied=threshold]")), "applied threshold explains its origin")
    pg.fill("input[name=threshold]", "0.8")
    ok(any("0.8 — this source's setting for this sound" in t for t in text(pg, "[data-applied=threshold]")), "explicit value overrides the offset")
    pg.fill("input[name=min_volume_dbfs]", "-30")
    ok(any("-30 dBFS" in t for t in text(pg, "[data-applied=min_volume_dbfs]")), "volume gate applied")
    pg.click("button[data-action=apply]")
    n_saves = pg.evaluate("window.__state.saves.length")
    pg.click(".savebar button[data-action=save]")
    pg.wait_for_function(f"window.__state.saves.length > {n_saves}")
    g = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "garden")
    ok(list(g["classes"].values())[0] == {"threshold": 0.8, "min_volume_dbfs": -30}, "per-source settings saved")

    # detail at "all sources" level: result per source, clip-forbidden class, schedule choice, advice
    pg.select_option("select[name=scope]", "")
    pg.fill("input[name=search]", "Speech")
    pg.locator("li[data-mid='/m/09x0r'] button[data-action=settings]").click()
    pg.wait_for_selector("sound-recognition-sounds sr-class-detail")
    ok(any("Clips are never kept" in t for t in text(pg, ".warn")) and pg.locator("input[name=clip_retention_days]").count() == 0, "clip-forbidden class explained, no retention field")
    pg.click("button:has-text('Back to the list')")
    pg.fill("input[name=search]", "Bark")
    pg.locator("li[data-mid='/m/05tny_'] button[data-action=settings]").click()
    pg.wait_for_selector("sr-class-detail table")
    pg.fill("input[name=threshold]", "0.7")
    thr = text(pg, "tbody tr")
    ok(thr[0].startswith("KitchenYes0.7") and thr[1].startswith("Garden cameraYes0.8"), "result per source includes each source's offset and own settings")
    pg.check("input[name=sched][value=times]")
    pg.wait_for_selector("sr-class-detail sr-schedule-grid .cell")
    pg.screenshot(path=os.path.join(OUT, "sounds-detail.png"), full_page=True)
    pg.click("button[data-action=apply]")
    pg.fill("input[name=search]", "")
    pg.fill("input[name=search]", "Smoke detector")
    pg.locator("li[data-mid='/m/01y3hg'] input[name=global]").check()
    pg.locator("li[data-mid='/m/01y3hg'] button[data-action=settings]").click()
    pg.wait_for_selector("sr-class-detail .advice li.danger", timeout=3000)
    ok(any("Add the beeps class too" in t for t in text(pg, ".advice li")), "service advice for this sound shown")
    pg.click("button:has-text('Back to the list')")
    pg.fill("input[name=search]", "")
    pg.screenshot(path=os.path.join(OUT, "sounds-list.png"), full_page=True)
    pg.close()

    # ------------------------------------------------------------------ advice tab
    def advice_cards(page, section=None):
        return page.locator("sound-recognition-advice li.advice")

    pg = new("", "light", 1200, 900)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=advice]")
    pg.wait_for_selector("sound-recognition-advice li.advice")
    def open_display(page):
        page.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-advice').shadowRoot.querySelectorAll('details.display').forEach((d) => { d.open = true; })")
    ok(advice_cards(pg).count() == 6 and pg.locator("sound-recognition-advice li.advice[data-kind=recommendation]").count() == 2, "warnings and recommendations are listed together")
    order = pg.evaluate("[...document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-advice').shadowRoot.querySelectorAll('li.advice')].map((e) => e.dataset.status)")
    ok(order[0] == "todo" and order.index("info") > order.index("todo") and "todo" not in order[order.index("info"):], "what can be applied comes first, then the information")
    first_info = pg.locator("sound-recognition-advice li.advice[data-status=info] .badge").first
    ok(first_info.inner_text().strip().lower() == "danger", f"information is sorted by level ({first_info.inner_text()!r})")
    ok(pg.locator("sound-recognition-advice li.advice[data-kind=recommendation] details.display").count() == 0, "a recommendation has no display setting")
    ok(pg.locator("sound-recognition-advice li.advice[data-status=todo] button[data-action=apply]").count() == 1 and pg.locator("sound-recognition-advice li.advice[data-status=info] button[data-action=apply]").count() == 0, "a button only where there is a gesture")
    open_display(pg)
    pg.locator("li.advice[data-rule=speech_target][data-source=kitchen] select[data-scope=all]").select_option("info")
    badges = [b for b in text(pg, "li.advice.info .badge")]
    ok(sum("Information" in b for b in badges) == 4, "global level applies to every source (preview before saving)")
    ok(pg.locator("sound-recognition-advice .savebar").count() == 1, "advice change marks unsaved")
    pg.locator("li.advice[data-rule=speech_target][data-source=kitchen] select[data-scope=kitchen]").select_option("ignore")
    ok(pg.locator("sound-recognition-advice li.advice.hidden").count() == 1, "hiding for one source moves it to the hidden section")
    n_saves = pg.evaluate("window.__state.saves.length")
    pg.click(".savebar button[data-action=save]")
    pg.wait_for_function(f"window.__state.saves.length > {n_saves}")
    cfg = pg.evaluate("window.__state.saves.at(-1)")
    k = next(x for x in cfg["sources"] if x["id"] == "kitchen")
    ok(cfg["advice"] == {"speech_target": "info"} and k["advice"] == {"speech_target": "ignore"}, "global and per-source advice levels saved")
    # a safety advice needs confirmation
    open_display(pg)
    pg.locator("li.advice[data-rule=fire_only] select[data-scope=kitchen]").select_option("ignore")
    ok(pg.locator("sound-recognition-advice .confirm").count() == 1 and pg.locator("sound-recognition-advice .savebar").count() == 0, "hiding a safety advice asks first and changes nothing yet")
    pg.click("button[data-action=cancel-hide]")
    ok(pg.locator("sound-recognition-advice .confirm").count() == 0, "confirmation can be cancelled")
    ok(pg.locator("li.advice[data-rule=fire_only] select[data-scope=kitchen]").input_value() == "inherit", "menu shows the real setting after cancelling")
    open_display(pg)
    pg.locator("li.advice[data-rule=fire_only] select[data-scope=kitchen]").select_option("ignore")
    pg.click("button[data-action=confirm-hide]")
    pg.click(".savebar button[data-action=save]")
    pg.wait_for_function(f"window.__state.saves.length > {n_saves + 1}")
    k = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "kitchen")
    ok(k["advice"]["fire_only"] == {"level": "ignore", "confirm": True}, "confirmed safety advice saved with confirm: true")
    ok(pg.locator("sound-recognition-advice li.advice.hidden").count() == 2, "hidden advice stays listed so it can be restored")
    pg.locator("li.advice[data-rule=speech_target][data-source=kitchen] select[data-scope=kitchen]").select_option("inherit")
    ok(pg.locator("sound-recognition-advice li.advice.hidden").count() == 1, "restoring brings the advice back")
    ok(pg.locator("li.advice[data-rule=speech_target][data-source=kitchen] select[data-scope=kitchen]").input_value() == "inherit" and pg.locator("li.advice[data-rule=speech_target][data-source=garden] select[data-scope=garden]").input_value() == "inherit", "each menu shows its own advice's setting after moves between sections")
    pg.screenshot(path=os.path.join(OUT, "advice.png"), full_page=True)
    pg.close()

    # ------------------------------------------------------------------ clips tab
    pg = new("", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=clips]")
    pg.wait_for_selector("sound-recognition-clips li[data-event]")
    rows = lambda: pg.locator("sound-recognition-clips li[data-event]").count()
    ok(rows() == 4 and pg.locator("sound-recognition-clips audio").count() == 4, "clips listed with players")
    ok(any("Kept until" in t for t in text(pg, ".what")), "expiry shown")
    ok(text(pg, "li[data-event=e1] [data-size]") == ["2 MB"] and text(pg, "li[data-event=e3] [data-size]") == ["150 KB"], "each clip shows its size")
    ok(text(pg, "[data-summary]") == ["4 clips · 3.8 MB"] and "All clips take 3.8 MB on the disk; 8 GB free." in text(pg, "[data-disk]")[0], "total of the selection and disk usage")
    pg.select_option("select[name=source]", "garden")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('li[data-event]').length == 3")
    ok(text(pg, "[data-summary]") == ["3 clips · 3.6 MB"], "filter by source: totals follow")
    pg.select_option("select[name=source]", "")
    pg.select_option("select[name=usage]", "animals")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('li[data-event]').length == 3")
    names = pg.evaluate("[...document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('select[name=sound] option')].map(o => o.textContent.trim())")
    ok(names[0] == "All sounds" and any(n.startswith("Bark (2)") for n in names) and not any("Smoke" in n for n in names), f"filter by category (animals): sounds offered are those of the category {names}")
    pg.select_option("select[name=usage]", "")
    pg.select_option("select[name=sound]", "/m/01y3hg")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('li[data-event]').length == 1")
    ok(rows() == 1, "filter by sound")
    pg.select_option("select[name=sound]", "")
    pg.fill("input[name=from]", "2000-01-01")
    pg.fill("input[name=to]", "2000-01-02")
    pg.wait_for_selector("sound-recognition-clips p.note")
    ok(rows() == 0 and pg.locator("button[data-action=delete-matching]").count() == 0, "a period without clips: nothing to delete by filter")
    pg.fill("input[name=from]", "")
    pg.fill("input[name=to]", "")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('li[data-event]').length == 4")
    pg.screenshot(path=os.path.join(OUT, "clips.png"), full_page=True)

    # deleting one clip: confirmation first, nothing happens when cancelled
    pg.locator("li[data-event=e3] button[data-action=delete-one]").click()
    ok("Delete this clip (150 KB)?" in text(pg, "[data-confirm]")[0], "one clip: confirmation with its size")
    pg.click("button[data-action=cancel]")
    ok(pg.locator("[data-confirm]").count() == 0 and rows() == 4 and pg.evaluate("window.__state.clipCalls.filter(c => c[0] == 'delete').length") == 0, "cancelled: nothing deleted")
    pg.locator("li[data-event=e3] button[data-action=delete-one]").click()
    pg.click("button[data-action=confirm]")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('li[data-event]').length == 3")
    ok(pg.evaluate("window.__state.clipCalls.filter(c => c[0] == 'delete').at(-1)") == ["delete", "e3", False] and "1 clips deleted, 150 KB freed." in text(pg, "[data-result]")[0], "one clip deleted, result shown")

    # selection
    pg.locator("li[data-event=e1] input[name=pick]").check()
    pg.locator("li[data-event=e4] input[name=pick]").check()
    ok(text(pg, "[data-picked]") == ["2 selected · 2.6 MB"] and pg.is_enabled("button[data-action=delete-selected]"), "selection: count and size")
    pg.click("button[data-action=delete-selected]")
    ok("Delete 2 clips (2.6 MB)?" in text(pg, "[data-confirm]")[0], "selection: confirmation names the count and the size")
    pg.click("button[data-action=confirm]")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('li[data-event]').length == 1")
    ok(pg.evaluate("window.__state.clipCalls.filter(c => c[0] == 'delete').at(-1)") == ["delete", "e1,e4", False], "selection: the chosen ids are sent")
    pg.close()

    # everything matching the filters, and everything
    pg = new("", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=clips]")
    pg.wait_for_selector("sound-recognition-clips li[data-event]")
    ok(pg.locator("button[data-action=delete-all]").count() == 1 and pg.locator("button[data-action=delete-matching]").count() == 0, "without filters: only 'all' is offered")
    pg.select_option("select[name=usage]", "animals")
    pg.fill("input[name=from]", pg.evaluate("new Date(Date.now() - 10 * 86400000).toISOString().slice(0, 10)"))
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('li[data-event]').length == 2")
    ok(text(pg, "[data-summary]") == ["2 clips · 2.6 MB"], "category and period combined")
    pg.click("button[data-action=delete-matching]")
    pg.wait_for_selector("[data-confirm]")
    ok("Delete 2 clips (2.6 MB)?" in text(pg, "[data-confirm]")[0] and pg.evaluate("window.__state.clipCalls.filter(c => c[0] == 'delete').at(-1)")[2] is True, "filter: the service counts first (dry run) and the confirmation shows it")
    ok(pg.evaluate("window.__state.clipRows.length") == 4, "nothing deleted before the confirmation")
    pg.click("button[data-action=confirm]")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('li[data-event]').length == 0")
    ok(pg.evaluate("window.__state.clipRows.map(r => r.id)") == ["e3", "e5"], "only the clips matching category and period are gone (the 20-day-old bark and the smoke stay)")
    pg.select_option("select[name=usage]", "")
    pg.fill("input[name=from]", "")
    pg.wait_for_selector("button[data-action=delete-all]")
    pg.click("button[data-action=delete-all]")
    pg.wait_for_selector("[data-confirm]")
    ok("Delete every clip (3, 1.2 MB)" in text(pg, "[data-confirm]")[0], "everything: confirmation with the count and size on disk")
    pg.click("button[data-action=confirm]")
    pg.wait_for_selector("sound-recognition-clips p.note")
    ok(pg.evaluate("window.__state.clipRows.length") == 0 and pg.locator("button[data-action=delete-all]").count() == 0, "everything deleted")
    pg.close()

    pg = new("?manyclips=1", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=clips]")
    pg.wait_for_selector("sound-recognition-clips li[data-event]")
    ok(pg.locator("sound-recognition-clips li[data-event]").count() == 100, "clips: first page of 100")
    pg.click("button[data-action=more]")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-clips').shadowRoot.querySelectorAll('li[data-event]').length == 130")
    ok(pg.locator("button[data-action=more]").count() == 0, "clips: the rest is loaded on demand")
    pg.check("input[name=selectPage]")
    ok(text(pg, "[data-picked]") == ["130 selected · 130 KB"], "select the clips shown")
    pg.close()

    # ------------------------------------------------------------------ overview tab
    pg = new("", "light", 1200, 1000)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=insights]")
    pg.wait_for_selector("sound-recognition-insights .card")
    ok(pg.locator("sound-recognition-insights .card").count() == 3, "overview: one card per enabled source")
    garden = text(pg, ".card[data-source=garden]")[0]
    ok("Ambient -50 dBFS (usually -60)" in garden and "Normal thresholds" in garden, "overview: ambient level against the usual one, thresholds normal")
    ok("Detected 4" in garden and "Hidden by raised thresholds 5" in garden and "Marked false 1" in garden, "overview: counts of the last 24 hours per source")
    ok(text(pg, "[data-stat=detected]") == ["7"] and text(pg, "[data-stat=hidden]") == ["5"] and text(pg, "[data-stat=false]") == ["1"], "overview: totals")
    ok(pg.locator("[data-chart] .col").count() == 24, "overview: hourly chart with one column per hour")
    ok(pg.locator("sound-recognition-insights li[data-rule]").count() == 0 and pg.locator("sound-recognition-insights button[data-action=apply]").count() == 0, "overview: no separate recommendation list, they are in the Advice tab")
    ok(any("2 advice items need attention" in t for t in text(pg, "[data-advice] p")), "overview: one summary of what needs attention (what can be applied and the warnings)")
    pg.evaluate("window.__push({type:'context', source:'garden', active_contexts:['/m/07c52'], ambient_dbfs:-40, baseline_dbfs:-60, adaptive_enabled:true, adaptive_offset:0.07})")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-insights').shadowRoot.querySelector('.card[data-source=garden] [data-thresholds]').textContent.includes('+0.22')")
    thr = text(pg, ".card[data-source=garden] [data-thresholds]")[0]
    ok("context sound + ambient noise" in thr, "overview: thresholds raised by the context boost plus the ambient offset, with the causes")
    ok(any("Television" in c for c in text(pg, ".card[data-source=garden] [data-contexts] .chip")), "overview: context sound heard is shown")
    pg.evaluate("window.__push({type:'masked', id:'m1', source:'garden', mid:'/m/05tny_', class:'Bark', score:0.6, threshold:0.65, base_threshold:0.5, offset:0.15, reasons:['context'], detected_at:new Date().toISOString()})")
    pg.evaluate("window.__push({type:'detection', id:'d1', source:'kitchen', mid:'/m/05tny_', class:'Bark', score:0.9, duration_s:2, detected_at:new Date().toISOString()})")
    pg.wait_for_selector("sound-recognition-insights .timeline li[data-kind=detection]")
    tl = text(pg, ".timeline li")
    ok(any("Television heard" in x or "Television" in x for x in tl) and any("hidden on Garden camera: score 0.60, needed 0.65 (context sound)" in x for x in tl) and any("detected on Kitchen" in x for x in tl), "overview: live timeline of context, hidden and detected sounds")
    pg.screenshot(path=os.path.join(OUT, "insights.png"), full_page=True)
    n_saves = pg.evaluate("window.__state.saves.length")
    pg.click("button[data-action=open-advice]")
    pg.wait_for_selector("sound-recognition-advice li.advice[data-rule=enable_contexts]")
    ok(pg.locator("li.advice[data-rule=enable_contexts]").get_attribute("data-status") == "todo", "advice: not applied yet, so it has its button")
    pg.locator("li[data-rule=enable_contexts] button[data-action=apply]").click()
    pg.wait_for_function(f"window.__state.saves.length > {n_saves}")
    g = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "garden")
    ok(list(g["classes"].values()) == [{"enabled": True}], "advice: applying a recommendation saves its patch on that source")
    pg.wait_for_selector("li.advice[data-rule=enable_contexts][data-status=applied]", state="attached")
    ok(pg.locator("li.advice[data-rule=enable_contexts] button[data-action=apply]").count() == 0 and "Already applied" in text(pg, "li.advice[data-rule=enable_contexts] .state")[0], "advice: once applied it says « Already applied » instead of the button")
    ok(pg.locator("sound-recognition-advice details[data-applied-group]").count() == 1 and "Already applied (1)" in text(pg, "details[data-applied-group] summary")[0], "advice: applied items are in a folded group, with their count")
    ok(pg.locator("sound-recognition-advice details[data-applied-group]").get_attribute("open") is None, "advice: the applied group is folded")
    pg.click("button[data-tab=insights]")
    pg.wait_for_selector("sound-recognition-insights [data-advice]")
    ok(any("1 advice item needs attention" in t for t in text(pg, "[data-advice] p")), "overview: the count goes down once it is applied")
    pg.close()

    pg = new("?lang=fr", "dark", 1200, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=insights]")
    pg.wait_for_selector("sound-recognition-insights .card")
    ok(any("Dernières 24 heures" in t for t in text(pg, "h2")) and any("Conseils" in t for t in text(pg, "h2")) and any("Ouvrir l'onglet Conseils" in t for t in text(pg, "button[data-action=open-advice]")), "French overview")
    pg.close()

    # ------------------------------------------------------------------ service updates
    def banner(pg):
        return pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update')?.shadowRoot?.querySelector('[data-update]')?.dataset.update ?? null")
    def banner_text(pg):
        return pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update').shadowRoot.querySelector('[data-update]').textContent.replace(/\\s+/g, ' ')")
    pg = new("?upd=available", "light", 1200, 800)
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update')?.shadowRoot?.querySelector('[data-update]')")
    ok(banner(pg) == "available" and "0.1.0 → 0.2.0" in banner_text(pg) and "v0.2.0" not in banner_text(pg), "update: banner says a newer service version exists")
    pg.screenshot(path=os.path.join(OUT, "update-available.png"))
    pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update').shadowRoot.querySelector('button.go').click()")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update').shadowRoot.querySelector('[data-update=installing]')")
    ok(pg.evaluate("window.__state.installs") == 1, "update: one click launches the update once")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update').shadowRoot.querySelector('[data-update=done]')")
    ok("updated to 0.2.0 and is back online" in banner_text(pg), "update: tells when the service is back")
    pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update').shadowRoot.querySelector('button.x').click()")
    pg.wait_for_timeout(100)
    ok(banner(pg) is None, "update: banner goes away once closed and nothing is left to update")
    pg.close()

    pg = new("?upd=fail", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-update >> [data-update=available]")
    pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update').shadowRoot.querySelector('button.go').click()")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update').shadowRoot.querySelector('[data-update=failed]')")
    ok("boom" in banner_text(pg) and "git said no" in pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update').shadowRoot.querySelector('pre').textContent"), "update: failure shows the reason and the log")
    pg.close()

    pg = new("?upd=manual&lang=fr", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-update >> [data-update=available]")
    ok(pg.evaluate("!!document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-update').shadowRoot.querySelector('button.go')") is False
       and "git pull && bash install.sh" in banner_text(pg) and "Une nouvelle version" in banner_text(pg), "update: without the helper, the command to run is shown (French)")
    pg.close()

    pg = new("?upd=outdated", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-update >> [data-update=outdated]")
    ok("older than this panel expects" in banner_text(pg), "update: an outdated service is flagged")
    pg.close()

    pg = new("?upd=none", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.wait_for_timeout(200)
    ok(banner(pg) is None, "update: no banner when the service is current")
    pg.close()

    # ------------------------------------------------------------------ "not a real sound"
    pg = new("", "light", 1200, 900)
    pg.wait_for_selector("sound-recognition-live .events li")
    pg.locator("li[data-event=e1] button[data-action=false]").click()
    raise_btn = pg.locator("li[data-event=e1] button[data-action=mark-raise]")
    ok("raise the threshold to 0.94 on Garden camera" in raise_btn.text_content(), "false detection: proposal is just above the score")
    n_saves = pg.evaluate("window.__state.saves.length")
    raise_btn.click()
    pg.wait_for_selector("li[data-event=e1] [data-false-chip]")
    g = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "garden")
    ok(pg.evaluate("window.__state.saves.length") == n_saves + 1 and g["classes"]["/m/05tny_"] == {"threshold": 0.94}, "false detection: threshold raised on that source and sound only")
    ok(pg.evaluate("window.__state.feedback") == [["e1", True]], "false detection: marked in the service")
    pg.locator("li[data-event=e1] button[data-action=unmark]").click()
    pg.wait_for_function("window.__state.feedback.length == 2")
    ok(pg.evaluate("window.__state.feedback.at(-1)") == ["e1", False] and pg.locator("li[data-event=e1] [data-false-chip]").count() == 0, "false detection: can be undone")
    pg.locator("li[data-event=e3] button[data-action=false]").click()
    pg.locator("li[data-event=e3] button[data-action=mark-only]").click()
    pg.wait_for_selector("li[data-event=e3] [data-false-chip]")
    ok(pg.evaluate("window.__state.saves.length") == n_saves + 1, "false detection: marking alone changes no setting")
    pg.close()

    # ------------------------------------------------------------------ context sounds group and place
    pg = new("", "light", 1200, 900)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.evaluate("window.__state.config.sources[1].environment = 'living_tv'")
    pg.click("button[data-tab=sounds]")
    pg.wait_for_selector("sound-recognition-sounds [data-context-group]")
    ctx = text(pg, "li.inctx .name strong")
    ok(len(ctx) == 5 and "Television" in ctx and "Radio" in ctx and "Music" in ctx, "sounds: the 5 context sounds that change thresholds are grouped on top")
    ok(pg.locator("sound-recognition-sounds .list >> nth=1").locator("li.inctx").count() == 0, "sounds: and not repeated in the main list")
    pg.select_option("select[name=scope]", "garden")
    ok(any("Recommended for Living room (TV, music)" in t for t in text(pg, "[data-context-rec]")), "sounds: recommendation for the place of the chosen source")
    pg.click("button[data-action=enable-contexts]")
    pg.click(".savebar button[data-action=save]")
    pg.wait_for_function("window.__state.saves.length >= 1")
    g = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "garden")
    ok(sorted(g["classes"].values(), key=str) == [{"enabled": True}] * 3, "sounds: one click enables the recommended context sounds on that source")
    ok(pg.locator("[data-action=enable-contexts]").count() == 0, "sounds: nothing left to recommend")
    pg.screenshot(path=os.path.join(OUT, "sounds-context.png"), full_page=False)
    pg.close()

    pg = new("", "light", 1200, 1000)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("sound-recognition-sources li[data-source]")
    pg.click("li[data-source=garden] button[data-action=edit]")
    pg.wait_for_selector("select[name=environment]")
    ok("Living room (TV, music)" in text(pg, "select[name=environment] option") and "Garage, workshop" in text(pg, "select[name=environment] option"), "sources: kinds of place offered")
    pg.select_option("select[name=environment]", "living_tv")
    ok(pg.locator("details[data-tips] li").count() == 3, "sources: tips for the chosen place")
    pg.check("input[name=adaptive]")
    pg.fill("input[name=adaptiveMax]", "0.2")
    pg.click("button[data-action=save]")
    pg.wait_for_function("window.__state.saves.length >= 1")
    g = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "garden")
    ok(g["environment"] == "living_tv" and g["adaptive"] == {"enabled": True, "max_offset": 0.2} and g["threshold_offset"] == 0.1, "sources: place and adaptive sensitivity saved, other settings kept")
    pg.click("li[data-source=garden] button[data-action=edit]")
    pg.wait_for_selector("select[name=environment]")
    ok(pg.input_value("select[name=environment]") == "living_tv" and pg.is_checked("input[name=adaptive]") and pg.input_value("input[name=adaptiveMax]") == "0.2", "sources: saved values come back in the form")
    pg.select_option("select[name=environment]", "")
    pg.uncheck("input[name=adaptive]")
    pg.click("button[data-action=save]")
    pg.wait_for_function("window.__state.saves.length >= 2")
    g = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "garden")
    ok("environment" not in g and g["adaptive"]["enabled"] is False, "sources: place cleared, adaptive switched off")
    pg.close()

    # ------------------------------------------------------------------ rooms, devices and links
    pg = new("", "light", 1200, 1000)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("sound-recognition-sources li[data-source]")
    ok(text(pg, "section.links h2") == ["Connected rooms"] and pg.locator("[data-hs=install]").count() == 1 and pg.locator("[data-manager]").count() == 0, "rooms: without Home Structure, its installation is recommended first")
    ok("describe your home once for all of them" in text(pg, "[data-hs=install] p")[0] and pg.get_attribute("a[data-action=hs-github]", "href").endswith("schawki/ha-home-structure"), "rooms: the recommendation says why and links to Home Structure")
    pg.close()
    pg = new("?hs=ready", "light", 1200, 1000)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("sound-recognition-sources li[data-source]")
    pg.click("li[data-source=garden] button[data-action=edit]")
    pg.wait_for_selector("select[name=area]")
    ok(pg.locator("[data-devices]").count() == 0 and any("Choose a room" in t for t in text(pg, "fieldset.room .dim")), "devices: nothing listed before a room is chosen")
    pg.select_option("select[name=area]", "entree")
    pg.wait_for_selector("[data-device]", state="attached")
    ok(text(pg, "[data-devsummary] p")[0] == "0 in the room, 1 in connected rooms." and "Salon (70 %)" in text(pg, "[data-neighbours]")[0], "devices: an automatic summary, with the connected rooms and the share of sound that reaches the source")
    ok(pg.locator("[data-expert][open]").count() == 0 and not pg.locator("label.dev").first.is_visible(), "devices: the detailed list is an expert setting, folded by default")
    ok("Automatic (no type in Home Structure)" in text(pg, "select[name=environment] option")[0] and "has no type for « Entrée »" in text(pg, "[data-place-help]")[0], "place: a room without a type in Home Structure says so")
    pg.click("[data-expert] summary")
    ok(sorted(pg.evaluate("[...document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-sources').shadowRoot.querySelectorAll('[data-device]')].map(e => e.dataset.device)")) == ["media_player.tv", "media_player.tv_2"], "devices: devices of the room and of the rooms connected to it in the Home Structure plan")
    ok(any("TV Salon" in t and "Salon" in t for t in text(pg, "label.dev")) and any("same device as media_player.tv" in t for t in text(pg, "div.dev")), "devices: room shown for devices of other rooms, duplicates folded")
    pg.select_option("select[name=area]", "salon")
    pg.wait_for_function("window.__state.deviceCalls.at(-1)[0] == 'salon'")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-sources').shadowRoot.querySelector('[data-place-help]').textContent.includes('Living room')")
    ok("Automatic: Living room (TV, music)" in text(pg, "select[name=environment] option")[0] and "Deduced from the type of the room in Home Structure (Living room)" in text(pg, "[data-place-help]")[0], "place: deduced from the type of the room in Home Structure, and kept in step with it")
    ok(pg.locator("details[data-tips] li").count() == 3, "place: the tips of the deduced place are shown")
    pg.check("input[name=devEnabled]")
    pg.fill("input[name=devMax]", "0.2")
    pg.locator("label.dev[data-device='media_player.tv'] input").uncheck()
    pg.fill("textarea[name=devInclude]", "switch.hood\nfan.extractor")
    n_saves = pg.evaluate("window.__state.saves.length")
    pg.click("button[data-action=save]")
    pg.wait_for_function(f"window.__state.saves.length > {n_saves}")
    g = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "garden")
    ok("environment" not in g, "place: automatic means nothing is stored")
    ok(g["area"] == "salon" and g["devices"] == {"enabled": True, "max_offset": 0.2, "exclude": ["media_player.tv"], "include": ["switch.hood", "fan.extractor"]} and g["threshold_offset"] == 0.1, "devices: room, activation, limit, exclusions and extra entities saved, other settings kept")
    pg.click("li[data-source=garden] button[data-action=edit]")
    pg.wait_for_selector("label.dev")
    ok(pg.input_value("select[name=area]") == "salon" and pg.is_checked("input[name=devEnabled]") and pg.input_value("input[name=devMax]") == "0.2" and not pg.locator("label.dev[data-device='media_player.tv'] input").is_checked(), "devices: saved values come back in the form")
    pg.fill("textarea[name=devInclude]", "")
    pg.uncheck("input[name=devEnabled]")
    pg.select_option("select[name=area]", "")
    pg.locator("button[data-action=save]").click()
    pg.wait_for_function(f"window.__state.saves.length > {n_saves + 1}")
    g = next(x for x in pg.evaluate("window.__state.saves.at(-1)")["sources"] if x["id"] == "garden")
    ok("area" not in g and g["devices"]["enabled"] is False and "include" not in g["devices"], "devices: room cleared and device setting switched off")
    pg.screenshot(path=os.path.join(OUT, "rooms.png"), full_page=True)
    pg.close()

    # Home Structure there, ready: its description is read, not edited here
    pg = new("?hs=ready", "light", 1200, 1000)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("[data-hs=managed]")
    ok(pg.locator("[data-manager]").count() == 0 and pg.locator("select[name=linkA]").count() == 0, "home structure: nothing to edit here")
    rows = text(pg, "li[data-hs-link]")
    ok(len(rows) == 2 and "Salon ↔ Entrée" in rows[0] and "Open space (no separation) · open" in rows[0] and "Entrée ↔ Entrée (extérieur)" in rows[1] and "Door · closed" in rows[1], "home structure: connections, separations and their state are shown")
    ok(pg.get_attribute("a[data-action=hs-open]", "href") == "/config/integrations/integration/home_structure", "home structure: link to its configuration")
    ok(pg.get_attribute("a[data-action=hs-edit]", "href") == "/home-structure", "home structure: link to the plan editor")
    ok(pg.evaluate("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-sources').shadowRoot.querySelector('structure-plan').shadowRoot.querySelectorAll('.box').length") == 3, "home structure: the plan is drawn read-only with its three spaces")
    plan = pg.evaluate("[...document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-sources').shadowRoot.querySelector('structure-plan').shadowRoot.querySelectorAll('.pill')].map(p => p.dataset.sepType + ':' + p.dataset.state)")
    ok(plan == ["open_space:open", "door:closed", "glass_door:open", "grille:unknown"], f"home structure: every separation is drawn with its state {plan}")
    tips = pg.evaluate("[...document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-sources').shadowRoot.querySelector('structure-plan').shadowRoot.querySelectorAll('.pill title')].map(t => t.textContent)")
    ok("Security grille: unknown" in tips and "Glass or sliding door: open · Roller shutter: partly open" in tips, f"home structure: tooltips name the separation, its state and its shutter {tips}")
    kinds = pg.evaluate("[...document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-sources').shadowRoot.querySelector('structure-plan').shadowRoot.querySelectorAll('text.type')].map(t => t.textContent)")
    ok(kinds == ["Living room", "Building hall"], f"home structure: the type of each space is shown under its name {kinds}")
    pg.screenshot(path=os.path.join(OUT, "hs-plan.png"))
    pg.close()

    pg = new("?hs=ready&oldhs=1", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("[data-hs=managed]")
    ok(pg.locator("[data-plan=old]").count() == 1 and "Update Home Structure" in text(pg, "[data-plan=old]")[0], "home structure without positions: asked to update it, the list stays")
    pg.close()

    for query, kind, expect in (("?hs=setup", "setup", "Home Structure is installed"), ("?hs=empty", "empty", "describes nothing yet")):
        pg = new(query, "light", 1200, 800)
        pg.wait_for_selector("sound-recognition-live .card")
        pg.click("button[data-tab=sources]")
        pg.wait_for_selector(f"[data-hs={kind}]")
        ok(expect in text(pg, f"[data-hs={kind}]")[0] and pg.locator("[data-manager]").count() == 0, f"home structure {kind}: told what to do, nothing can be described here")
        pg.close()
    pg = new("?hs=setup", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("[data-hs=setup]")
    ok(pg.get_attribute("a[data-action=hs-add]", "href") == "/config/integrations/dashboard/add?domain=home_structure", "home structure: link to add the integration")
    pg.close()

    pg = new("", "light", 1200, 1000)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=insights]")
    pg.wait_for_selector("sound-recognition-insights .card")
    pg.evaluate("window.__push({type:'context', source:'garden', active_contexts:[], ambient_dbfs:-50, baseline_dbfs:-60, adaptive_enabled:true, adaptive_offset:0, external_offset:0.08, external_reasons:['device','shared'], external_detail:[{label:'TV Salon · 100 %', value:0.08}, {label:'Kitchen: Television · 70 %', value:0.05}]})")
    pg.wait_for_function("document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-insights').shadowRoot.querySelector('.card[data-source=garden] [data-devices]')")
    ok("TV Salon · 100 % +0.08" in text(pg, ".card[data-source=garden] [data-devices]")[0] and "Kitchen: Television · 70 % +0.05" in text(pg, ".card[data-source=garden] [data-devices]")[0], "overview: devices and neighbouring rooms behind the raise, with their share")
    thr = text(pg, ".card[data-source=garden] [data-thresholds]")[0]
    ok("+0.08" in thr and "devices in the room + sound heard in a neighbouring room" in thr, "overview: thresholds include the devices, causes named")
    pg.evaluate("window.__push({type:'masked', id:'m2', source:'garden', mid:'/m/05tny_', class:'Bark', score:0.55, threshold:0.6, base_threshold:0.5, offset:0.1, reasons:['device','shared'], detected_at:new Date().toISOString()})")
    pg.wait_for_function("[...document.querySelector('sound-recognition-panel').shadowRoot.querySelector('sound-recognition-insights').shadowRoot.querySelectorAll('.timeline li')].some(l => l.textContent.includes('devices in the room'))")
    pg.close()

    pg = new("?lang=fr", "dark", 390, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("sound-recognition-sources li[data-source]")
    ok(text(pg, "section.links h2") == ["Pièces reliées"] and any("Décrivez votre logement avec Home Structure" in t for t in text(pg, "[data-hs=install] strong")), "rooms: French")
    pg.click("li[data-source=garden] button[data-action=edit]")
    pg.wait_for_selector("select[name=area]")
    pg.select_option("select[name=area]", "salon")
    pg.wait_for_selector("[data-device]", state="attached")
    ok(pg.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "rooms: form fits a phone")
    pg.close()

    # ------------------------------------------------------------------ keyboard
    pg = new("", "light", 1200, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.focus("button[data-tab=live]")
    pg.keyboard.press("ArrowRight")
    pg.wait_for_selector("sound-recognition-insights")
    pg.keyboard.press("ArrowRight")
    pg.wait_for_selector("sound-recognition-sources")
    ok(pg.get_attribute("button[data-tab=sources]", "aria-selected") == "true", "tabs follow the arrow keys")
    pg.keyboard.press("End")
    pg.wait_for_selector("sound-recognition-clips")
    ok(pg.get_attribute("button[data-tab=clips]", "aria-selected") == "true", "End goes to the last tab")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("sound-recognition-sources li[data-source]")
    pg.click("li[data-source=kitchen] button[data-action=edit]")
    pg.wait_for_selector("sr-schedule-grid .grid")
    before = pg.locator("sr-schedule-grid .cell.on").count()
    pg.focus("sr-schedule-grid .grid")
    pg.keyboard.press("Space"); pg.keyboard.press("ArrowRight"); pg.keyboard.press("Space")
    ok(pg.locator("sr-schedule-grid .cell.on").count() == before + 2, "the schedule grid works with the keyboard")
    ok("Mon 00:00" in (pg.get_attribute("sr-schedule-grid #c0", "aria-label") or "") or "Mon" in (pg.get_attribute("sr-schedule-grid #c0", "aria-label") or ""), "cells have readable labels")
    pg.close()

    # a warning whose gesture a recommendation already offers for the same sounds is one advice, not two
    pg = new("?fix=1", "light", 1200, 900)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=advice]")
    pg.wait_for_selector("sound-recognition-advice li.advice")
    ok(pg.locator("li.advice[data-rule=detonations_fireworks]").count() == 0 and advice_cards(pg).count() == 6, "advice: a warning that duplicates a recommendation is shown once, as the recommendation")
    pg.close()
    pg = new("?fix=2", "light", 1200, 900)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=advice]")
    pg.wait_for_selector("sound-recognition-advice li.advice")
    ok(pg.locator("li.advice[data-rule=detonations_fireworks][data-status=todo] button[data-action=apply]").count() == 1 and advice_cards(pg).count() == 7, "advice: a warning with its own gesture shows an Apply button")
    pg.locator("li.advice[data-rule=detonations_fireworks] button[data-action=apply]").click()
    pg.wait_for_selector("li.advice[data-rule=detonations_fireworks][data-status=applied]", state="attached", timeout=8000)
    ok(pg.locator("li.advice[data-rule=detonations_fireworks] button[data-action=apply]").count() == 0, "advice: the warning says it is applied right after the click")
    pg.close()

    pg = new("?lang=fr", "dark", 1200, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=advice]")
    pg.wait_for_selector("sound-recognition-advice li.advice")
    ok(any("Danger" in b for b in text(pg, "li.advice .badge")) and any("Niveau du catalogue" in t for t in text(pg, "option")) and "Affichage" in text(pg, "details.display summary")[0] and any(t == "Appliquer" for t in text(pg, "button[data-action=apply]")), "French advice tab")
    pg.screenshot(path=os.path.join(OUT, "advice-dark-fr.png"))
    pg.close()

    pg = new("?lang=fr&narrow=1", "dark", 390, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sounds]")
    pg.wait_for_selector("sound-recognition-sounds li[data-mid]")
    ok(any("516 sons" in t for t in text(pg, ".dim")) and any("Alerte recommandée" in t for t in text(pg, "li[data-mid] .name")), "French sounds tab")
    ok(pg.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "sounds list fits a phone")
    pg.screenshot(path=os.path.join(OUT, "sounds-phone-fr.png"), full_page=False)
    pg.close()

    pg = new("?narrow=1&lang=fr", "dark", 390, 800)
    pg.wait_for_selector("sound-recognition-live .card")
    pg.click("button[data-tab=sources]")
    pg.wait_for_selector("sound-recognition-sources li[data-source]")
    pg.click("li[data-source=kitchen] button[data-action=edit]")
    pg.wait_for_selector("sr-schedule-grid .cell")
    ok(pg.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "form fits a phone without page scroll")
    ok(any("Écoute" in t for t in text(pg, "legend")), "French form")
    pg.screenshot(path=os.path.join(OUT, "sources-phone-fr.png"), full_page=True)
    pg.close()

    for q, msg in (("?fail=unreachable", "cannot be reached"), ("?fail=not_loaded", "is not set up")):
        pg = new(q)
        pg.wait_for_timeout(500)
        ok(any(msg in t for t in text(pg, ".note")), f"error state: {msg}")
        pg.close()
    ok(not errors, "no console errors" + (": " + "; ".join(errors[:3]) if errors else ""))
    b.close()
sys.exit(1 if ok.failed else 0)
